export class Product {
  $key: string;
  productId: number;
  productName: string;
  productCategory: string;
  productPrice: number;
  productDiscount: 0;
  productDescription: string = null;
  productMaterial: string = null;
  productSize: string = null;
  productStyle: string = null;
  productOrigin: string = null;
  productManufacturer: "n/a";
  productDesigner: string = null;
  productTime: string = null;
  productCondition: string = null;
  productImageUrl: string = null;
  productImageUrl2: string = null;
  productImageUrl3: string = null;
  productImageUrl4: string = null;
  productImageUrl5: string = null;
  productImageUrl6: string = null;
  productImageUrl7: string = null;
  productImageUrl8: string = null;
  productImageAlt: string = null;
  productAdded: number;
  productAvailable = true;
  productQuantity = 1;
  productActive = true;
  productSold = false;
  favourite: boolean;
}
